// <auto-generated />
namespace Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class seededUsersandLecturer3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seededUsersandLecturer3));
        
        string IMigrationMetadata.Id
        {
            get { return "201612221059127_seededUsersandLecturer3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
